name: Build, test & upload new version

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Setup environment
        run: |
          python -m pip install packaging pipenv psutil
          python setup.py setup
      - name: Run tests
        run: python setup.py test
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Setup environment
        run: |
          python -m pip install packaging pipenv psutil
          python setup.py setup
      - name: Build
        run: python setup.py build
      #Cache
      - name: Get pip cache dir
        id: pipenv-cache
        run: |
          echo "dir=$(pipenv --venv)" >> $GITHUB_OUTPUT
      - uses: actions/cache/save@v3
        with:
          path: ${{ steps.pipenv-cache.outputs.dir }}
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: Windows Installer
          path: dist/discord.fm*setup*.exe
