name: Build, test & upload new version

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Setup environment
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install libcairo-dev libgirepository1.0-dev python3-gi gobject-introspection gir1.2-gtk-3.0 gir1.2-appindicator3-0.1
          fi
          python -m pip install packaging pipenv psutil
          python setup.py setup
      - name: Build
        run: python setup.py build
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }} dist files
          path: dist/discord.fm-*
  test:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    # TODO: Add cache support
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Setup environment
        shell: bash
        run: |
          python -m pip install packaging pipenv psutil
          python setup.py setup
      - name: Run tests
        run: python setup.py test
